// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRnNeWXKnp6yuDQ5EsR1dMbI-95FSsUpM',
    appId: '1:423073884390:web:fc15fbdf6d098e4386b327',
    messagingSenderId: '423073884390',
    projectId: 'wall-app-2a7ff',
    authDomain: 'wall-app-2a7ff.firebaseapp.com',
    storageBucket: 'wall-app-2a7ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGDGTknI4F9nQufIixI8EzZhMWFQFdjmA',
    appId: '1:423073884390:android:3840a9722ca2490086b327',
    messagingSenderId: '423073884390',
    projectId: 'wall-app-2a7ff',
    storageBucket: 'wall-app-2a7ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-7Zf7OAuWgt0sANIiwODjPooBnB8j_Fw',
    appId: '1:423073884390:ios:e34da611565a882b86b327',
    messagingSenderId: '423073884390',
    projectId: 'wall-app-2a7ff',
    storageBucket: 'wall-app-2a7ff.appspot.com',
    iosClientId: '423073884390-fqf48lupn67atlosjcc37opc4s1bscu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-7Zf7OAuWgt0sANIiwODjPooBnB8j_Fw',
    appId: '1:423073884390:ios:f7d42dcaa86fc35786b327',
    messagingSenderId: '423073884390',
    projectId: 'wall-app-2a7ff',
    storageBucket: 'wall-app-2a7ff.appspot.com',
    iosClientId: '423073884390-vr3fes7poaq2vdtv5iah2l1iva5e5fe7.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallApp.RunnerTests',
  );
}
